# Generated by Django 5.1.2 on 2024-11-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_DB',
            fields=[
                ('Customer_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Loan_no', models.IntegerField()),
                ('Loan_amount', models.IntegerField()),
                ('Mail_ID', models.EmailField(max_length=254)),
            ],
        ),
    ]
